import type { SiteConfig } from '~/types/content'
import { publishedPosts } from '~/data/posts'

/**
 * Global site configuration.
 *
 * The domain is used to build canonical URLs, the sitemap, and the RSS feed —
 * change it here if the site ever moves off GitHub Pages.
 */
export const site: SiteConfig = {
  domain: 'https://iammuttaqi.github.io',
  title: 'Muntaser Muttaqi — Software Engineer',
  description:
    'Software engineer building web applications in Laravel. Lead Web Engineer at Gymscanner. Livewire, Filament, Inertia and Vue, with the occasional side project that escapes.',
  ogImage: '/og-image.svg',
  locale: 'en',
  themePreference: 'light',
  analyticsId: 'G-XXXXXXXXXX',

  nav: [
    { label: 'Work', to: '/projects', icon: 'i-lucide-layout-grid' },
    { label: 'About', to: '/about', icon: 'i-lucide-user' },
    { label: 'Writing', to: '/writing', icon: 'i-lucide-pen-line' },
    { label: 'Contact', to: '/contact', icon: 'i-lucide-mail' }
  ],

  footer: {
    text: 'Built with Nuxt, Nuxt UI and far too much coffee. Deployed on GitHub Pages.',
    copyrightHolder: 'Muntaser Muttaqi',
    startYear: 2020
  },

  contact: {
    email: 'muntasermuttaqi@gmail.com',
    responseTime: 'Usually within 24 hours on weekdays'
  },

  socials: [
    { label: 'GitHub', handle: '@iammuttaqi', url: 'https://github.com/iammuttaqi', icon: 'i-simple-icons-github' },
    { label: 'LinkedIn', handle: 'in/iammuttaqi', url: 'https://linkedin.com/in/iammuttaqi', icon: 'i-simple-icons-linkedin' },
    { label: 'X', handle: '@iammuttaqi', url: 'https://x.com/iammuttaqi', icon: 'i-simple-icons-x' },
    { label: 'Packagist', handle: 'iammuttaqi', url: 'https://packagist.org/packages/iammuttaqi/', icon: 'i-simple-icons-packagist' },
    { label: 'Fiverr', handle: 'iammuttaqi', url: 'https://www.fiverr.com/iammuttaqi', icon: 'i-simple-icons-fiverr' },
    { label: 'Discord', handle: 'iammuttaqi', url: 'https://discord.com/users/657308086679109652', icon: 'i-simple-icons-discord' }
  ],

  // Generated by printing /resume to PDF; bump updatedAt whenever you re-export.
  resume: {
    file: '/resume/muntaser-muttaqi-cv.pdf',
    updatedAt: '2026-08-02'
  },

  notFound: {
    code: '404',
    title: 'This route is not registered',
    description: 'The page you asked for was never bound to the container.',
    hint: 'php artisan route:list'
  },

  feeds: {
    rss: '/rss.xml',
    sitemap: '/sitemap.xml'
  }
}

export const currentYear = new Date().getFullYear()

/**
 * The Writing entry drops out of the header and footer while there are no
 * published posts, so the nav never points at an empty page. Restore the posts
 * in app/data/posts.ts and it comes back on its own.
 */
export const visibleNav = site.nav.filter(item => item.to !== '/writing' || publishedPosts.length > 0)
